In [ ]:
import pandas as pd
import numpy as np
import seaborn as sbs
import matplotlib as plt

In [ ]:
df = pd.read_csv(r"C:\Users\sebas\Desktop\etl_depo_rosario\AA1-TUIA-Munoz-Onyskiw-Calenta\weatherAUS_2026C1.csv")
df

,Unnamed: 0,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow,RainfallTomorrow
0,0,2008-12-01,Albury,13.6,22.5,0.6,NaN,NaN,W,45.0,...,23.8,1008.1,1007.2,8.0,NaN,16.8,20.8,No,No,0.0
1,1,2008-12-02,Albury,7.3,25.8,0.0,NaN,NaN,WNW,44.0,...,22.1,1011.1,1007.5,NaN,NaN,18.3,24.6,No,No,0.0
2,2,2008-12-03,Albury,13.2,26.2,0.0,NaN,NaN,WSW,46.0,...,31.5,1007.3,1009.4,NaN,2.0,21.2,23.4,No,No,0.0
3,3,2008-12-04,Albury,10.0,28.8,0.0,NaN,NaN,NE,23.0,...,18.5,1017.6,1012.4,NaN,NaN,17.4,26.3,No,No,1.0
4,4,2008-12-05,Albury,17.4,32.4,1.0,NaN,NaN,W,41.0,...,34.6,1010.9,1005.9,7.0,8.0,17.9,29.1,No,No,0.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145407,145454,2017-06-20,Uluru,2.6,22.0,0.0,NaN,NaN,E,29.0,...,26.5,1024.8,1021.2,NaN,NaN,10.1,21.6,No,No,0.0
145408,145455,2017-06-21,Uluru,3.1,23.2,0.0,NaN,NaN,E,31.0,...,24.7,1024.3,1020.5,NaN,NaN,11.1,21.5,No,No,0.0
145409,145456,2017-06-22,Uluru,3.6,26.0,0.0,NaN,NaN,NNW,21.0,...,21.4,1023.3,1018.4,NaN,NaN,11.8,24.5,No,No,0.0
145410,145457,2017-06-23,Uluru,4.8,27.4,0.0,NaN,NaN,N,39.0,...,23.7,1021.0,1016.0,NaN,NaN,12.0,26.9,No,No,0.0
145411,145458,2017-06-24,Uluru,7.5,26.5,0.0,NaN,NaN,SE,28.0,...,27.1,1019.8,1016.2,3.0,2.0,14.7,26.8,No,No,0.0

In [4]:
df.columns

Index(['Unnamed: 0', 'Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall',
       'Evaporation', 'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am',
       'WindDir3pm', 'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am',
       'Humidity3pm', 'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm',
       'Temp9am', 'Temp3pm', 'RainToday', 'RainTomorrow', 'RainfallTomorrow'],
      dtype='str')

In [13]:
df.describe(include='all')

,Unnamed: 0,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow,RainfallTomorrow
count,145412.000000,145412,145412,143928.000000,144159.000000,142152.000000,82658.000000,75616.000000,135096,135159.000000,...,140907.000000,130351.000000,130388.000000,89542.000000,86076.000000,143646.000000,141805.000000,142152,142153,142153.000000
unique,NaN,3435,49,NaN,NaN,NaN,NaN,NaN,16,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,NaN
top,NaN,2013-03-01,Canberra,NaN,NaN,NaN,NaN,NaN,W,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,No,NaN
freq,NaN,49,3435,NaN,NaN,NaN,NaN,NaN,9910,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110276,110281,NaN
mean,72728.184393,NaN,NaN,12.196528,23.223064,2.361516,5.468616,7.611241,NaN,40.036668,...,51.532206,1017.647237,1015.255080,4.447287,4.509770,16.991981,21.683360,NaN,NaN,2.361242
std,41990.722236,NaN,NaN,6.417956,7.135927,8.479338,4.193871,3.785612,NaN,13.648259,...,20.844414,7.113833,7.044507,2.887161,2.720306,6.509191,6.953072,NaN,NaN,8.479084
min,0.000000,NaN,NaN,-9.700000,-5.100000,0.000000,0.000000,0.000000,NaN,6.000000,...,0.000000,980.300000,977.400000,0.000000,0.000000,-8.000000,-5.800000,NaN,NaN,0.000000
25%,36362.750000,NaN,NaN,7.600000,17.900000,0.000000,2.600000,4.800000,NaN,31.000000,...,36.600000,1012.900000,1010.400000,1.000000,2.000000,12.300000,16.600000,NaN,NaN,0.000000
50%,72727.500000,NaN,NaN,12.000000,22.600000,0.000000,4.800000,8.400000,NaN,38.000000,...,52.000000,1017.600000,1015.200000,5.000000,5.000000,16.700000,21.100000,NaN,NaN,0.000000
75%,109093.250000,NaN,NaN,16.900000,28.200000,0.800000,7.400000,10.600000,NaN,48.000000,...,65.700000,1022.400000,1020.000000,7.000000,7.000000,21.600000,26.400000,NaN,NaN,0.800000
max,145458.000000,NaN,NaN,34.100000,49.100000,371.000000,145.000000,14.500000,NaN,135.000000,...,100.000000,1041.200000,1039.800000,9.000000,9.000000,39.800000,47.000000,NaN,NaN,371.000000

De las columnas presentes se puede entender que representan lo siguiente:  
unnamed = Esta columna debe ser el index original de la misma
Date = Fecha  
Location = Ubicación  
MinTemp = Temperatura Minima en ºC  
MaxTemp = Temperatura Máxima en ºC  
Rainfall = cantidad de lluvia en el periodo de 24hs en mm  
Evaporation = Evaporación de liquido en un recipiente abierto en un periodo de 24hs en mm  
Sunshine = cantidad de horas de sol en el día  
WindGustDir = Dirección de ráfagas de viento, expresada en dirección cardinal, se entiende que habla de ráfaga máxima   
WindGustSpeed = Velocidad del viento en esa ráfaga, expresada en km/h  
WindDir9am/3pm = Dirección del viento, expresada en dirección cardinal, en esos respectivos horarios  
WindSpeed9am/3pm = Velocidad del viento en esos respectivos horarios en km/h  
Humidity9am/3pm = Humedad en ese horario, en %  
Pressure9am/3pm = Presión atmosferica en ese horario, en hPa  
cloud9am/3pm = Variable Categorica que expresa tipo de Nube en ese momento  
Temp9am/3pm = Temperatura en ese horario, en ºC  
RainToday = si ha llovido hoy  
RainTomorrow = si va a llover mañana  
RainfallTomorrow =cuanta cantidad se espera de lluvia mañana?  

Se ha usado información del Australian National Bureau of Meteorology para poder entender correctamente el significado de cada variable

In [14]:
df.isnull().sum()

Unnamed: 0              0
Date                    0
Location                0
MinTemp              1484
MaxTemp              1253
Rainfall             3260
Evaporation         62754
Sunshine            69796
WindGustDir         10316
WindGustSpeed       10253
WindDir9am          10562
WindDir3pm           4226
WindSpeed9am         1767
WindSpeed3pm         3061
Humidity9am          2653
Humidity3pm          4505
Pressure9am         15061
Pressure3pm         15024
Cloud9am            55870
Cloud3pm            59336
Temp9am              1766
Temp3pm              3607
RainToday            3260
RainTomorrow         3259
RainfallTomorrow     3259
dtype: int64

teniendo columnas con hasta 69k de datos faltantes se descarta la opción de eliminar las entradas que presenten nulos ya que se considera que esto afectaría a la calidad del trabajo.

In [15]:
df.nunique()

Unnamed: 0          145412
Date                  3435
Location                49
MinTemp                395
MaxTemp                506
Rainfall               681
Evaporation            358
Sunshine               145
WindGustDir             16
WindGustSpeed          120
WindDir9am              16
WindDir3pm              16
WindSpeed9am            76
WindSpeed3pm            75
Humidity9am            983
Humidity3pm            995
Pressure9am            547
Pressure3pm            542
Cloud9am                10
Cloud3pm                10
Temp9am                446
Temp3pm                503
RainToday                2
RainTomorrow             2
RainfallTomorrow       681
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(0)